
name: Test

on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/test.yml'
      - 'index.js'
      - 'conf/*'
      - 'hooks/*'



concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  testsshfs:
    if: ${{ !contains(github.repository, 'solaris') && !contains(github.repository, 'dragonflybsd')}}
    strategy:
      matrix:
        release: [ "7.3", ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: A job to run test sshfs OpenBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v3
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@main
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          pkg_add curl
        mem: 2048
        copyback: false
        release: ${{ matrix.release }}
        nat: |
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        sync: sshfs
        run: |
          tree .
          tree $HOME/work/

  test:
    strategy:
      matrix:
        release: [ "7.3", ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: A job to run test OpenBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v3
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@main
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          pkg_add curl
        mem: 2048
        copyback: false
        release: ${{ matrix.release }}
        nat: |
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        run: |

          pwd
          ls -lah
          whoami
          env
          
          










